### ISSUE TITLE
[Blood]  Broken Vsync, fps limit can't be turned off and high cpu usage

### ISSUE THREAD

**Issue by Milan978** [nukeykt/NBlood#714] opened 2023-05-18 11:10 UTC
1. When I set vsync to on it won't stay on next time I enter the game cause I can see screen tearing so it must be set to on again. 

2. Fps limiter can't be set to off only 30.

3. Cpu usage on some cores goes to 70% like I'm playing some modern game. Blood is from 97 so it should be max 5% on each core.

**Comment by CommonLoon102** [comment] 2023-05-19 06:29
Your third point is not valid. The game is CPU heavy and it is perfectly normal to use 100% of 1 core. It was the same in 1997, but in 320x200.

**Comment by Milan978** [comment] 2023-05-19 09:20
It's not one core but all of them. Resident Evil 4 remake uses less cpu and it's has ten times more advanced physics. Look at the pictures below. This is not normal.
![nblood](https://github.com/nukeykt/NBlood/assets/40280170/a0e31ee8-5371-44ca-883e-978a280d43d9)
![RE4](https://github.com/nukeykt/NBlood/assets/40280170/383d2f22-4d9b-4d64-8852-abcdc5fbabd9)

**Comment by CommonLoon102** [comment] 2023-05-19 16:25
This is normal. Modern games are using the GPU, even for physics. Blood is using the CPU, especially if you are running it with software renderer, then it won't even use the GPU at all.

**Comment by Milan978** [comment] 2023-05-19 21:02
No, this is not normal. Game that is made in 97 to work on Pentium 75 and has sprites, lowres textures and very simple physics now suddenly needs to use 70% of each core on modern cpu. Yeah, right!  It's a fact that this port is far from perfect in this current state and I hope that all this will be fixed in the future.

**Comment by CommonLoon102** [comment] 2023-05-20 10:55
I doubt that it is using 70% of EACH core, since the game is single-threaded. It cannot run on multiple cores.

**Comment by Milan978** [comment] 2023-05-20 11:49
Look at the picture above if you have any doubts. Riva Tuner doesn't lie. Single core game will use all cores unless you set core affinity to one core with some software like Process Lasso. Even if it's 70% of one core it's still too much to for a game game that old. The next thing you gonna tell me is that it should also compile shaders for two hours like that crappy Last Of Us Playstation port.

**Comment by CommonLoon102** [comment] 2023-05-20 12:48
I've just tried the latest build. For me, nblood.exe is using 1 core only. I have 4 cores, and nblood.exe is using about 26-28% only (data is from task manager). Your measurements might be incorrect. You should close background apps for example.

> Even if it's 70% of one core it's still too much to for a game game that old.
No, there is no direct connection between a game's release date and the CPU clocks it can utilize.

**Comment by Jan200101** [comment] 2023-05-20 13:14
> Single core game will use all cores unless you set core affinity to one core

This is a load of nonsense.

Windows (and a lot of other operating systems) is multitasking and thus constantly stopping and starting programs so multiple things can run at the same time.

Pinning the process to a single core could improve performance by not having to move data around the cache, but chances are its probably going to hurt performance by insisting on using a specific core, which the OS will share with other programs.

In regards to the screenshots above, note that NBlood runs at a higher framerate, uses a lower CPU frequency, less memory and basically no GPU resources.

This is an apples to oranges comparison and I suggest you read up about the things you talk about.

**Comment by Milan978** [comment] 2023-05-20 14:50
I just did another quick test using latest 64bit version like before. When I am on desktop and all background apps are closed cpu usage is 0-1%. When I start the game(all background apps are closed) and let the demos run first 2 cores are around 30%-35% and the other 2 are 50%-70%. So as you can see Jan200101 I am not speaking nonsense. Single core games do use more than one core. I don't have time at the moment to install some other old games to make screenshots for you to see that they also are using all four cores but not 70%. They use much, much less. This port is just horribly optimized and that's a fact.

**Comment by Jan200101** [comment] 2023-05-20 14:54
> ... and let the demos run first 2 cores are around 30%-35% and the other 2 are 50%-70%

are you sure you aren't using a 2 core CPU with hyper threading, giving you 4 logical cores in total?

**Comment by Milan978** [comment] 2023-05-20 14:57
Jesus! Take a look at the picture below.

![CPUZ](https://github.com/nukeykt/NBlood/assets/40280170/d7572e28-c8c9-4299-876e-95f51c84d258)

**Comment by CommonLoon102** [comment] 2023-05-20 19:42
I have a 4 core Haswell as well. Are you sure you don't have a virus or something? For me nblood.exe is using 26-28% as I said... I'm on Windows 7 though.

**Comment by Milan978** [comment] 2023-05-21 00:35
I am on Win10 22H2. I don't have any viruses and everything else works fine except nblood. Riva Tuner in combination with MSI Afterburner is very well known and reliable combination for overclocking, monitoring, scanline sync, etc.

**Comment by CommonLoon102** [comment] 2023-05-21 07:49
OK. And what the task manager is showing? What percentage for nblood.exe?

**Comment by CommonLoon102** [comment] 2023-05-21 07:57
To set the FPS limit to any value, open the console and then:
```
r_showfps 3
r_vsync 0
r_maxfps 500
```

**Comment by CommonLoon102** [comment] 2023-05-21 08:03
With setting the max fps to 1000, I have constant 1000 FPS in game, while the process is using 32-38% CPU. Does the Resident Evil 4 remake render stable 1000 FPS for you?

**Comment by CommonLoon102** [comment] 2023-05-21 08:12
With setting the `r_maxfps` to `-2` the FPS is unlimited and I get 1800-2600 FPS. CPU usage is at 40% (on 4 core Haswell) at 2560x1440. Do you get better results in Resident Evil 4?

**Comment by CommonLoon102** [comment] 2023-05-21 08:16
Even with Software renderer, I get 100-120 FPS. I start Post Mortem on Extra Crispy, because there is action at the very beginning already. So I'm not just facing a wall but running round and dynamites flying everywhere.

**Comment by CommonLoon102** [comment] 2023-05-21 08:35
OK, I was able to reproduce your first 2 issues:
1. If you enable v-sync from the menu (instead of the console), it won't remember it next time you start the game.
2. There is no "unlimited" setting for FPS limiting in the menu. That's correct.

Just use the console as a workaround.

**Comment by Milan978** [comment] 2023-05-21 09:17
Task manager is not capable of displaying usage of every core so it's useless. How about you install Riva Tuner and MSI Afterburner and make some screenshots so we can see what's really happening? Why are you defending this bad port like your life is at stake? Why this spinlock isn't fixed? The only reason I put those pictures is to show that RE4 remake that is milion times more complex in every way than Blood works better which just proves my point that nblood is bad port.

**Comment by Milan978** [comment] 2023-05-21 10:53
The only reason why I am wasting my time on this port is because my friend who doesn't know sh*t about computers got a bit nostalgic and wanted to play Blood. He asked me if I could make the game work on his laptop so I did some quick research and found out that Nblood and Raze ports are the way to go. Raze is even worse than nblood regarding cpu usage. Bad things that caught my attention are broken vsync, limiter that can't be turned off and insane cpu usage so I reported them here. Now I am wasting my time trying to explain to you that nblood is badly optimized port and you still defending it.

**Comment by CommonLoon102** [comment] 2023-05-21 11:53
You have reported 3 things in one issue. That itself is not recommended, but anyway.

Your first issue regarding v-sync is well-known, there is already an issue about it. It seems that you haven't searched the issues for duplicates before opening a new one.
https://github.com/nukeykt/NBlood/issues/578
The workaround is to use the console. The setting will be saved if you set v-sync from the console.

Your second issue is obvious. The unlimited option is missing from the menu. The workaround is to use the console.

Your third issue is about CPU usage. You have been told to check the Windows task manager to see the real CPU usage, but you haven't done it. So, maybe you don't even have an issue, you just don't know how to check CPU usage.

Then, you have stated that "nblood is badly optimized port". You have based this statement on the fact that it is using more CPU than you would expect. Let me tell shed some light into this. Blood is using one core at 100%, whatever you do. This was an intentional design decision by the developers. They have put a spinlock in the main game loop (as I have already told you) because that reduced stuttering and therefore the gameplay is smoother. Is that the best way to do? I don't know, maybe not. Is it badly optimized? Maybe. Show us that you can do better and open a Pull Request which eliminates the spinlock and doesn't affect the smoothness of framerates. If you can do this, or if you can show any other ports which are at least as smooth as NBlood but with lower CPU usage, then you are right. I'm waiting for your measurements.

**Comment by Jan200101** [comment] 2023-05-21 12:00
> The only reason I put those pictures is to show that RE4 remake that is milion times more complex in every way than Blood works better which just proves my point that nblood is bad port.

If you looked at the pictures you would also see that RE4R uses more CPU, GPU resources as well as memory, increases the CPU clock speed, draws more watt, uses a modern graphics API with less overhead all while running at half the framerate of NBlood.

I suggest that, if you intend to act like you are owed something, you play [Blood™ Fresh Supply](https://store.steampowered.com/app/1010750/Blood_Fresh_Supply/)

**Comment by CommonLoon102** [comment] 2023-05-21 12:12
> I suggest that, if you intend to act like you are owed something, you play [Blood™ Fresh Supply](https://store.steampowered.com/app/1010750/Blood_Fresh_Supply/)

I just tried Crap Supply. On the same resolution, with AA and AO turned off, it is using 25% CPU (1 core at 100%) in case of Vulkan. If I change the renderer to OpenGL 3.2, then the CPU usage is 50%, even higher than NBlood's (40%).

**Comment by CommonLoon102** [comment] 2023-05-21 12:16
> Without providing additional information the maintainers here will not be able to address the issue. Other framerate/vsync issues [have been resolved in the past](https://github.com/nukeykt/NBlood/issues/468) thanks to issue creators being willing to help.

Actually, he doesn't have framerate or performance issues. His only issue is that some software (RivaTuner) draws some characters on top of the game which he doesn't like. He would like to see 5% instead of 60%. For that, I suggest altering RivaTuner itself, so you will see the numbers you want to see there.

**Comment by Milan978** [comment] 2023-05-21 15:38
No offense man but you are either stoopid or ignorant. I've presented you hard evidence that this port is badly optimised and you are insisting that I use inferior task manager for measuring game performance. Riva Tuner is de facto standard for measuring game performance and is used by professionals for ages. I've presented you with 2 pictures to show cpu usage on modern game that is 100 times more complex and Blood from 97. Forget about other stats and look only cpu usage. I turned advanced physics options in game that are using cpu and RE4 is still using less cpu than this shitty port. I can also cap the fps to 60 and cpu usage will still be less than for nblood. People like you are spreading lies and misinformation. I am sick of of lazy, whiny and incompetent developers that are publishing badly optimized games and saying that is something completely normal. If the maker of this port had any skills he would fix this sh*t but is obviously that he doesn't no how or he doesn't care. Like I said before I am testing this port just as a favor for a friend and I couldn't care less about shitty port.

**Comment by CommonLoon102** [comment] 2023-05-21 15:52
And what issues does the game create you because of the CPU usage? You cannot pay your electricity bills, or what?

**Comment by Milan978** [comment] 2023-05-21 15:56
Wow! What a great sense of humor you have!

**Comment by Milan978** [comment] 2023-05-21 15:58
Just admit that I destroyed you with hard evidence instead of using bad humor.

**Comment by Jan200101** [comment] 2023-05-21 16:08
> Just admit that I destroyed you with hard evidence instead of using bad humor.

You are making bad comparisons, claims that are not based in reality and demands from people contributing voluntarily.

I suggest that you play [Blood™ Fresh Supply](https://store.steampowered.com/app/1010750/Blood_Fresh_Supply/) instead.

**Comment by Milan978** [comment] 2023-05-21 16:17
You have no valid arguments in this fight and you know it. Also, I didn't demand anything from anybody. I am just pointing at obvious things. I have no intentions of playing Blood in any way shape or form. It was just a favor for a friend. Now I let you enjoy in this fantastic port.

**Comment by CommonLoon102** [comment] 2023-05-21 16:56
OK, then you can close this issue.

**Comment by dibollinger** [comment] 2023-05-21 20:31
> Just admit that I destroyed you with hard evidence instead of using bad humor.

> I have no intentions of playing Blood in any way shape or form. It was just a favor for a friend.

Thank you for admitting to being a troll.

**Comment by Milan978** [comment] 2023-05-21 21:59
For all of you idiots here defending nblood I recommend you to visit this page: https://veg.by/en/projects/nfs3/
Read carefully how good port is made. The game is from 98 and what this guy manage to pull off alone without any source code is just mind blowing. Compared to this nblood is pure crap.

**Closed** 2023-05-21 22:11 UTC
