### ISSUE TITLE
Building/Installing or Raspberry PI 

### ISSUE THREAD

**Issue by actraiser30** [nukeykt/NBlood#332] opened 2020-03-11 09:35 UTC
Hello are there any instructions to build on a raspberry pi ?

or i just build eduke32 and put the required files in eduke32 folder like this?
i wanted to play blood/redneck rampage and Exhumed but i cannot find and info to build them only the info to build eduke32 engine but after that what i do?

thanks

**Comment by Jan200101** [comment] 2020-03-11 13:01
cloning this respository and building using the [eduke32 wiki](https://wiki.eduke32.com/wiki/Building_EDuke32_on_Linux) should be enough though I can't tell how well it will run.
I can probably run some tests on my Raspberry Pi 3 and see if it runs well enough to be playable

**Comment by actraiser30** [comment] 2020-03-11 13:15
thanks you mean i clone NBlood and then in the same folder i clone eduke32 or i do it in seperate folders and overwrite the cloned eduke32 folder after with the cloned NBlood??

**Comment by Jan200101** [comment] 2020-03-11 14:17
There is no need to clone eduke32 to build NBlood as it's a fork of eduke32
Simple replace the step where you clone eduke32 with cloning NBlood

**Comment by Jan200101** [comment] 2020-03-11 17:17
alright I've done some testing myself and currently NBlood does not compile for the raspberry pi 3 duo to a upstream mistake
but even then it runs badly at anything higher than 800x600

**Comment by actraiser30** [comment] 2020-03-11 17:55
It's ok if it can run 800x600 it will be fine if you can put the compiled
archive or binary for the Raspberry Pi in your downloads with a warning
about higher resolution will be great.

Στις Τετ, 11 Μαρ 2020, 19:17 ο χρήστης Jan <notifications@github.com>
έγραψε:

**Comment by actraiser30** [comment] 2020-03-12 07:59
so if i campile eduke 32 in the line it has svn checkout https://svn.eduke32.com/eduke32

i replace it with: svn checkout https://github.com/nukeykt/NBlood.git ??

thats all i do different?

or i compile it with the second option: git svn clone https://github.com/nukeykt/NBlood.git  ??

thanks

**Comment by sirlemonhead** [comment] 2020-03-12 09:29
We're entirely on git here for NBlood etc so just use 'git clone https://github.com/nukeykt/NBlood.git'

Then to compile, just type 'make' to compile all the games/utils or 'make nblood' to just compile NBlood, or 'make rednukem' for Duke3D/Redneck games, 'make pcexhumed' etc.

You might need additional dependencies, which are outlined  here https://wiki.eduke32.com/wiki/Building_EDuke32_on_Linux

**Comment by actraiser30** [comment] 2020-03-12 09:52
thanks,and if i want to put all the game files there are specific folders after compile finish eg blood folder redneck folder etc ?

**Comment by CommonLoon102** [comment] 2020-03-12 18:58
Actually it is `make blood` (not nblood).

**Comment by actraiser30** [comment] 2020-03-12 19:43
if i want to complie everything eg blood redneck duke exhumed i only type make?

**Comment by Jan200101** [comment] 2020-03-12 20:59
yeah just typing Make works
as I previously mentioned there are some problems with compiling NBlood on a Raspberry Pi mainly the zpl header not having a proper return if it does not succeed and libatomic not being linked

Here is a patch that should fix those until a fix is pushed upstream
[0001-Fix-compilation-on-rpi.patch](https://github.com/nukeykt/NBlood/files/4326555/0001-Fix-compilation-on-rpi.txt)

**Comment by actraiser30** [comment] 2020-03-13 11:51
what excatly i do with the 0001-Fix-compilation-on-rpi.patch.txt file how i use it ??

**Comment by actraiser30** [comment] 2020-03-15 14:30
hi did you apply the patch upstream?

**Comment by dudleydes** [comment] 2020-03-15 15:15
@actraiser30
These are the commands I have used to compile blood on my Raspberry Pi 3:
```
git clone https://github.com/nukeykt/NBlood.git
cd NBlood
wget https://github.com/nukeykt/NBlood/files/4326555/0001-Fix-compilation-on-rpi.txt
patch < 0001-Fix-compilation-on-rpi.txt
make blood USE_OPENGL=0
```

I couldn't get the patch file to work so I looked though the patch and realised there are a couple of simple edits. Instead I used [STFP](https://retropie.org.uk/docs/First-Installation/#sftp) to manually edit the files as below:

1. This [line](https://github.com/nukeykt/NBlood/blob/master/Common.mak#L1020) in `Common.mak` needs to be changed to `    LIBS += -lrt -latomic`
2. This [line](https://github.com/nukeykt/NBlood/blob/master/source/build/include/zpl.h#L174) in `zpl.h` needs to be changed to ` return 0;`

Save and compile using the `make` command.

I am running NBlood at 640x480, like I do the other ports on my system. I found that making this setting in the display menu gave me three small windows across the top of the screen. After exiting, I edited `nblood.cfg` that you can find in `/home/pi/.config/nblood` (note: `.config` is a hidden folder) and changed the `ScreenMode` to 1.

I was also getting an ALSA underrun error and the sound was cutting out. In the sound menu, I changed the sample rate to 44100Hz and applied settings which seems to have fixed the issue.

@Jan200101
I noticed in the log file that NBlood detects my PS3 controller. I'm wondering if there is gamepad support in NBlood, in particular the analog sticks. There appears to be no option to configure in the control setup menu.

It's not a major issue as I use xboxdrv to map my controller in other ports so I would be happy to do likewise for NBlood.

**Comment by Jan200101** [comment] 2020-03-16 12:01
there is minor gamepad support in NBlood but all menu interactions still require a keyboard and mouse and there is no way to remap them yet #42

**Comment by actraiser30** [comment] 2020-11-21 15:21
> @actraiser30
> These are the commands I have used to compile blood on my Raspberry Pi 3:
> 
> ```
> git clone https://github.com/nukeykt/NBlood.git
> cd NBlood
> wget https://github.com/nukeykt/NBlood/files/4326555/0001-Fix-compilation-on-rpi.txt
> patch < 0001-Fix-compilation-on-rpi.txt
> make blood USE_OPENGL=0
> ```
> 
> I couldn't get the patch file to work so I looked though the patch and realised there are a couple of simple edits. Instead I used [STFP](https://retropie.org.uk/docs/First-Installation/#sftp) to manually edit the files as below:
> 
> 1. This [line](https://github.com/nukeykt/NBlood/blob/master/Common.mak#L1020) in `Common.mak` needs to be changed to `    LIBS += -lrt -latomic`
> 2. This [line](https://github.com/nukeykt/NBlood/blob/master/source/build/include/zpl.h#L174) in `zpl.h` needs to be changed to ` return 0;`
> 
> Save and compile using the `make` command.
> 
> I am running NBlood at 640x480, like I do the other ports on my system. I found that making this setting in the display menu gave me three small windows across the top of the screen. After exiting, I edited `nblood.cfg` that you can find in `/home/pi/.config/nblood` (note: `.config` is a hidden folder) and changed the `ScreenMode` to 1.
> 
> I was also getting an ALSA underrun error and the sound was cutting out. In the sound menu, I changed the sample rate to 44100Hz and applied settings which seems to have fixed the issue.
> 
> @Jan200101
> I noticed in the log file that NBlood detects my PS3 controller. I'm wondering if there is gamepad support in NBlood, in particular the analog sticks. There appears to be no option to configure in the control setup menu.
> 
> It's not a major issue as I use xboxdrv to map my controller in other ports so I would be happy to do likewise for NBlood.

dudleydes i run the game on a Rpi3 and have 1920x1980 resolution when i lower the resolution it becomes three small windows
i looked on the /home/pi/.config/nblood/config file and the ScreenMode its already set to 1 so what can i do to use lower resolution?

**Comment by actraiser30** [comment] 2020-12-01 07:32
Hello upon build on a Raspberry pi3 on Raspbian Stretch OS i got an error upon on rednukem build

failer building obj/rr/player.o from source/rr/src/player.cpp!
GNUmakefile:1517 recipe for target 'obj/rr/player.o' failed
make: *** [obj/rr/player.o] Error 1

the blood and pcexhumed builds are succefully build only the rednukem does this error

any suggestion on whats wrong?

**Comment by Jan200101** [comment] 2020-12-01 08:30
That is not a complete Traceback

Even then it is likely a Atomic problem
Consult this comment https://github.com/nukeykt/NBlood/issues/332#issuecomment-599223400

**Comment by symbios24** [comment] 2020-12-01 09:31
Thats the same comment here

**Comment by Jan200101** [comment] 2020-12-01 09:43
I am not going to spoonfeed explanations for something that could be solve with minimal programming knowledge, a text editor and the ability to google

I am not aware what exact problem @actraiser30 is having since he did not provide a full traceback to why his build failed but it is probably related to libatomic not being linked by default.
adding -latomic to the linker flags should be enough to solve it and the previously linked comment describes how to do so (and how to fix zpl but that was merged upstream to my knowledge)

**Comment by actraiser30** [comment] 2020-12-01 09:54
i did add/edit this two files and i get this error i managed to build blood and pcexhumed (before i add the lines i could not)
but rednukem is giving this error

**Comment by symbios24** [comment] 2020-12-01 10:22
I tried my self to build it by adding this lines to the files nblood an exhumed are working 
Rednukem building stops probably with the same error,i uploaded an image from the error

https://files.fm/u/qqgmuwxvx

**Comment by symbios24** [comment] 2020-12-02 12:54
I found a builded version about a month old but when i ran the rednukem i get a libm.so.6 / libc.so.6 Glibc_2.27 / Glibc_2.28 not found error
What libraries are missing here to install them?

**Comment by Jan200101** [comment] 2020-12-02 20:03
I have once again made a patch that fixes building and this time its more upstream compliant
[0001-Temporary-Fix-to-allow-building-on-the-Raspberry-PI.patch.txt](https://github.com/nukeykt/NBlood/files/5631708/0001-Temporary-Fix-to-allow-building-on-the-Raspberry-PI.patch.txt)

It compiles nblood, exhumed and rednukem
Compilation was tested on a Raspberry Pi 3 Model B using a freshly installed version of RaspiOS with the `5.4.51-v7+` kernel
Dependencies can be copy pasted from here [the Wiki](https://wiki.eduke32.com/wiki/Building_EDuke32_on_Linux#On_Debian_.2F_Ubuntu)

here is a list of commands to apply the patch

```
wget https://github.com/nukeykt/NBlood/files/5631708/0001-Temporary-Fix-to-allow-building-on-the-Raspberry-PI.patch.txt
git config user.name "Name"
git config user.email "email@example.com"
git am < 0001-Temporary-Fix-to-allow-building-on-the-Raspberry-PI.patch.txt
```

all my testing (and the patch) has been done on commit 20904d63266e6e49091a278cb2cad6d212e6e0d6

> Rednukem building stops probably with the same error,i uploaded an image with the error

I cannot recreate this behavior the gnu toolchain
please provide more information

**Comment by symbios24** [comment] 2020-12-03 07:06
Hello thanks but the whole error from wppear to finish is on the link below in the photo
https://files.fm/u/qqgmuwxvx
Did you saw it??
Did you also see the errors about the compiled version a month old that upon running shows this errors:libm.so.6 / libc.so.6 Glibc_2.27 / Glibc_2.28 
Thanks

**Comment by Jan200101** [comment] 2020-12-03 07:31
> Hello thanks but the whole error from appear to finish is on the link below in the photo
> https://files.fm/u/qqgmuwxvx
> Did you saw it??
I saw it and I cannot replicate it
Please provide more system information including:
- Raspberry Pi Model
- OS Version
- compiler and library version
 
> Did you also see the errors about the compiled version a month old that upon running shows this errors:libm.so.6 / libc.so.6 Glibc_2.27 / Glibc_2.28 not found
> Thanks
I am unaware of the current glibc versions shipped on your OS but they are incompatible

**Comment by symbios24** [comment] 2020-12-03 08:14
Raspberry pi 3B
Raspbian stretch
Not sure for the compiler but all the depends from 
the duke wiki are installed

**Comment by Jan200101** [comment] 2020-12-03 08:36
try updating your packages, it is possible the currently installed packages are out of date and incompatible with current upstream Nblood
outside of that I cannot help a lot without direct hardware access to try and find the cause

**Comment by symbios24** [comment] 2020-12-03 08:37
Os is fully updated do i need to do an rpi-update also?

**Comment by arrowgent** [comment] 2021-05-07 22:09
raspberry pi 4
raspbian 32bit os
armhf

everything compiled and runs fine
thanks for all the work done here

and other build issues please note if using aarch64/arm64 or armhf/32bit

**Closed** 2023-08-04 04:23 UTC
