### ISSUE TITLE
Error when loading a saved game

### ISSUE THREAD

**Issue by Matthaiks** [nukeykt/NBlood#86] opened 2019-07-21 14:52 UTC
E2M7: Bowels of the Earth

![NBloodCrash](https://user-images.githubusercontent.com/3577122/61592731-70c83c80-abd7-11e9-96ca-251e5ed0c049.png)

Save file:
[game0004.zip](https://github.com/nukeykt/NBlood/files/3414718/game0004.zip)

**Comment by Jan200101** [comment] 2019-07-21 20:49
I am able to reproduce a different error with the latest commit
![image](https://user-images.githubusercontent.com/15076013/61596842-e6003580-ac08-11e9-83af-fad9c94635e5.png)

**Comment by Matthaiks** [comment] 2019-07-24 16:14
E6M3: Public Storage

![NBloodCrash2](https://user-images.githubusercontent.com/3577122/61809932-85f2d480-ae3e-11e9-8457-ca49c8e10018.png)

Save file:
[game0003.zip](https://github.com/nukeykt/NBlood/files/3427766/game0003.zip)

**Comment by putridpete** [comment] 2019-08-01 03:57
I'd like to throw my hat in the ring and say that, much like Matthaiks, I also got the same error while playing E2M7: Bowels of the Earth.

![Screenshot 2019-07-31 23 55 33](https://user-images.githubusercontent.com/50641282/62264664-dd6ce380-b3ee-11e9-87e8-9559a5a781ff.png)


Save:
[game0000.zip](https://github.com/nukeykt/NBlood/files/3454834/game0000.zip)

**Comment by CommonLoon102** [comment] 2019-08-16 13:58
Do you try to load the saved game with the same build which was saved the file? I think saves might not work between different builds, even if the source is the same but different tool-chain was used.

**Comment by putridpete** [comment] 2019-08-16 21:51
I would say so, I've only used release 1.01 because I lack the knowledge of how to build from source.

**Comment by ericson98** [comment] 2020-11-27 07:40
Same thing happened to me. The game crashes after saving, with the following message:

![Crash](https://user-images.githubusercontent.com/75113521/100423299-c3322c80-3059-11eb-9f74-bd11482e926d.png)

It also corrupts the save file. The same error message shows up after trying to load the file. Goodbye progress.

**Comment by Hendricks266** [comment] 2024-06-10 23:58
Fixed by #820?

**Closed by Hendricks266** 2024-06-10 23:58 UTC
