### ISSUE TITLE
[NBlood] Downloaded zip files don't contain the executable

### ISSUE THREAD

**Issue by Eddie2077** [nukeykt/NBlood#609] opened 2022-07-17 21:59 UTC
I'm not sure why, but the executables aren't in the 32bit or 64bit zip files. 

![2022 07 17-17 54_01](https://user-images.githubusercontent.com/92492329/179426246-d5a125a0-8d59-46cc-b2de-f34961432138.png)
![2022 07 17-17 54](https://user-images.githubusercontent.com/92492329/179426247-0257ea12-ca74-4dfd-876e-8e4fccd489c1.png)

**Comment by NY00123** [comment] 2022-07-18 15:41
Hi, it looks like you got the files from this page, right? https://lerppu.net/wannabethesis/

As stated there, oasiz (who's not a member of this repository) should be contacted.

To explain the lack of files, EDuke32 had makefile changes which were later merged into the NBlood repository. No problem was observed for EDuke32, and at least for me, also not for NBlood; But oasiz's auto-builds are created on a different machine, and the NBlood auto-build failed due to the use of a different compiler version.

**Comment by CommonLoon102** [comment] 2022-07-18 16:36
Someone who has access should set up CI/CD for this repo. No external parties should be involved.

**Comment by Eddie2077** [comment] 2022-07-22 18:23
> Hi, it looks like you got the files from this page, right? https://lerppu.net/wannabethesis/
> 
> As stated there, oasiz (who's not a member of this repository) should be contacted.
> 
> To explain the lack of files, EDuke32 had makefile changes which were later merged into the NBlood repository. No problem was observed for EDuke32, and at least for me, also not for NBlood; But oasiz's auto-builds are created on a different machine, and the NBlood auto-build failed due to the use of a different compiler version.

Yeah, I got them from that page. Though that page doesn't seem to have any information related on how to contact oasiz, just that oasiz should be contacted in case an issue occurs. The issue with the auto-builds appears to be affecting the PCExhumed and Rednukem downloads as well, the executables just aren't there when I download and open the respective zip files.

**Comment by martyfender** [comment] 2022-07-25 12:07
There is no contact info for oasiz on his web page.

**Comment by NY00123** [comment] 2022-07-25 15:16
Before writing about contact info, I'll relay an additional update from oasiz.

So, the other day he left the country with the hardware in question, and as it turns out, remote ssh access to it stopped working about a day later. He can't even update the page to point to the most recently built exes. He might get someone else to have a look.

For now, you can simply download the auto-builds preceding the last one.

As for contacting him, he's in the Duke4.net Discord and forums.

**Comment by Eddie2077** [comment] 2022-07-25 15:35
> Before writing about contact info, I'll relay an additional update from oasiz.
> 
> So, the other day he left the country with the hardware in question, and as it turns out, remote ssh access to it stopped working about a day later. He can't even update the page to point to the most recently built exes. He might get someone else to have a look.
> 
> For now, you can simply download the auto-builds preceding the last one.
> 
> As for contacting him, he's in the Duke4.net Discord and forums.

I understand. I hope the page can be fixed, then.

It seems that the NBlood auto-build "20220613-13229" is the latest one that has an executable on my end, so I'll probably use that for the time being.

I think I still have a Duke4 forum account, so I'll contact him directly if another issue pops up regarding his page.

**Comment by NY00123** [comment] 2022-07-25 17:20
I'll also quote his messages from the Duke4.net Discord's #revision-logs channel, the one used for linking to auto-builds:

```
all svn revision log stuff is on pause for the time being, will return some time asap when I have time (later today).
This includes autobuild stuff and whatnot.
Maintenance stuffs

Update: will take longer due to x y z. Meanwhile use the existing ones. 
```

**Comment by oasiz-** [comment] 2022-08-02 19:51
This has been fixed by modifying a makefile, see: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96862

Toolchain needs to be updated but the kernel the current arch chroot environment runs on is too old for that.
Phasing this out has been a long time coming and I've been mostly waiting for a period of time where I can focus on this.

Anyway a proper way forward would probably be Gitlab's own CI/CD setup as this was intended as a stopgap solution until something better/official came along.

**Comment by NY00123** [comment] 2022-08-02 22:08
Thanks to anyone who was involved in updating oasiz' auto-builds page. I'll close this issue now.

**Closed by NY00123** 2022-08-02 22:08 UTC
