### ISSUE TITLE
Tchernobog invincible

### ISSUE THREAD

**Issue by Kimplul** [nukeykt/NBlood#103] opened 2019-08-14 08:06 UTC
Tchernobog is for some reason invincible. Worked fine on DOSBox but his hitbox seems to have bugged out in NBlood.
I did the most common debugging actions, restart computer, load level from new save, didn't work.

Debian 4.19.37-5+deb10u1, gcc 8.3.0 and SDL 2.0.9.

**Comment by CommonLoon102** [comment] 2019-08-14 11:57
I can reproduce this on the master branch using Windows 7.
Tchernobog can die in NBlood 1.01 official release, so something has happened since then.

**Comment by CommonLoon102** [comment] 2019-08-14 12:37
This commit makes Tchernobog invincible:
https://github.com/nukeykt/NBlood/commit/1823e29044ce03d38928fc60621a6ef400c5531a

**Comment by CommonLoon102** [comment] 2019-08-14 20:59
Actually it is possible to kill him, it just needs an insane amount of shots. He has 666 health on the easiest difficulty but something is wrong with him because it seems as he would have some strong armor or something.

**Comment by CommonLoon102** [comment] 2019-08-14 23:00
@NoOneBlood Do you have any idea which part is causing the issue? https://github.com/nukeykt/NBlood/commit/1823e29044ce03d38928fc60621a6ef400c5531a is a very huge merge and I couldn't find the place where it breaks Tchernobog.
The changelog mentions:

> Fix selecting target for tchg (player as target)

Could this be it? Where is the modification for this?

**Comment by CommonLoon102** [comment] 2019-08-15 08:38
OK, I don't know what I was looking at before, anyways:
Before that commit it had 511 HP, after the commit it has 12800 (on still kicking). So, this is the problem I guess.

**Comment by CommonLoon102** [comment] 2019-08-15 11:11
I got it... The bug is in actor.cpp, this:
`pXSprite->health = dudeInfo[nType].startHealth << 4`

Seems like a simple assignation, right?
The problem is that this bug is in the original too, it is just used as a feature there...
Thernobog has 800 starting health, you shift that left by 4 (multiplying with 16) you will get 12800. But pXSprite->health won't be 12800, it will be 512. How the hell? Because it is an unsigned 12 bit integer! So, the variable overflows (got truncated from 11 0010 0000 0000 (12800 as decimal) to 10 0000 0000 which is 512.

@NoOneBlood has changed the health member of the XSPRITE struct from 12 to 20 bit wide, I guess because he wanted to add support for enemies with much more health. This made Tchernobog really strong. He now has 12800 HP instead of 512.

**Comment by Kimplul** [comment] 2019-08-15 11:16
Whoa, really? That's a weird "feature" :D
But why is it bitshifted in the first place?

**Comment by nukeykt** [comment] 2019-08-15 11:20
Thanks for digging it up. I guess i need to set hp to 32 in the dudeInfo table as quick solution

**Comment by CommonLoon102** [comment] 2019-08-15 11:26
Why is it bit shifted?

Almost every value is some larger value in the game. I mean for example your full diving suit or beast vision value is not 100 in practice but a much larger number, I guess 3600. When you start using the item, this 3600 will be decreased until you stop using it. It will be decreased every time the game updates its state, it happens a lot of times per second of course. So this way the game can keep track the values (enemy health, fire duration, movement duration, anything) for things. The other approach would be to have just 100 and decrement it by a float number, but working with floats (not whole numbers) are much-much slower for the CPU, especially for older CPUs.

Why not store the actual value then (the value they wanted to use instead of 800) and then it wouldn't be needed to multiply by 16 (left shift by 4) every time? I guess they wanted to have human readable smaller numbers for initial values and bit shifting is a very cheap operation. By the way this method of having 2 numbers for things have caused other bugs already in the game.

**Comment by Kimplul** [comment] 2019-08-15 11:28
I see.
So can this issue be closed then?

**Comment by CommonLoon102** [comment] 2019-08-15 11:34
> 
> 
> I see.
> So can this issue be closed then?

I think you should only close it when the fix is committed to the master branch.

**Comment by Kimplul** [comment] 2019-08-15 11:35
Ok, thanks

**Comment by CommonLoon102** [comment] 2019-08-15 11:38
> 
> 
> Ok, thanks

Thanks for alpha testing!

**Comment by CommonLoon102** [comment] 2019-08-15 11:45
Now you can close: https://github.com/nukeykt/NBlood/commit/63aab47f565290d2d9c09cb778c9a92254abfe4b

And please fix the title from Tchernobod to Tchernobog, thanks :D

**Closed** 2019-08-15 11:53 UTC
