### ISSUE TITLE
No redneck fun on startup

### ISSUE THREAD

**Issue by BielBdeLuna** [nukeykt/NBlood#252] opened 2019-12-11 19:50 UTC
source/blood/src/screen.cpp(202): BLOOD.PAL not found (RFF files may be wrong version)

**Comment by Hendricks266** [comment] 2019-12-11 19:53
Redneck Rampage cannot be played with NBlood.exe. The code repositories have been merged, nothing more. #250

**Closed by Hendricks266** 2019-12-11 19:53 UTC

**Comment by BielBdeLuna** [comment] 2019-12-11 19:56
so why close it?

**Comment by Hendricks266** [comment] 2019-12-11 20:57
It's not a bug, and as far as documentation goes it's a duplicate of #250.

Try `make rednukem`.

**Comment by BielBdeLuna** [comment] 2019-12-11 22:51
ok
